version: "3.8"

services:
  fastapi-backend-rag:
    build:
      context: ./fastapi-backend-rag
    container_name: fastapi-backend-rag
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - ./fastapi-backend-rag/.env
    volumes:
      - ./fastapi-backend-rag:/app
    depends_on: []
    restart: unless-stopped

  streamlit-loader:
    build:
      context: ./fastapi-backend-rag
    container_name: streamlit-loader
    command: streamlit run streamlit_uploader.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    env_file:
      - ./fastapi-backend-rag/.env
    volumes:
      - ./fastapi-backend-rag:/app
    depends_on: []
    restart: unless-stopped

  astro-frontend:
    build:
      context: ./astro-frontend
    container_name: astro-frontend
    command: pnpm run preview --host 0.0.0.0 --port 3000
    ports:
      - "3000:3000"
    # volumes:
    #   - ./astro-frontend:/app
    environment:
      - NODE_ENV=production
    depends_on: []
    restart: unless-stopped
