version: "3.8"

services:
  fastapi-backend-rag:
    build:
      context: ./fastapi-backend-rag
    container_name: fastapi-backend-rag
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8020:8000"
    env_file:
      - ./fastapi-backend-rag/.env
    volumes:
      - ./fastapi-backend-rag:/app
    depends_on: []
    restart: unless-stopped

  streamlit-loader:
    build:
      context: ./fastapi-backend-rag
    container_name: streamlit-loader
    command: streamlit run streamlit_uploader.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8521:8501"
    env_file:
      - ./fastapi-backend-rag/.env
    volumes:
      - ./fastapi-backend-rag:/app
    depends_on: []
    restart: unless-stopped

  astro-frontend:
    build:
      context: ./astro-frontend
      args:
        VITE_API_URL: "http://astro.look4experts.com/ask"
    container_name: astro-frontend
    ports:
      - "3020:80"
    environment:
      - NODE_ENV=production
    depends_on: []
    restart: unless-stopped